

import { Inter } from "next/font/google";
import "./globals.css";
import { AuthContextProvider } from "@/context/AuthContext";
import { Header } from "@/Components/Header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Bleksi Task",
  description: "Generated by create next app",
   
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContextProvider>
          <Header />
          <main>{children}</main>
        </AuthContextProvider>
      </body>
    </html>
  );
}
